### PR TITLE
Issue 31b

### PR DESCRIPTION
**Pull request by ghost**
added a (right-click) context menu to the domain view to copy user name and password to clipboard.

### CODE REVIEW

**Comment by 607011** [comment]
Thx, @egbrt! Cherry-picked f73dea4. Please do not add further commits to this pull-request, as it will produce next to unrecoverable merge conflicts.

If you'd like to continue your work on #31 in "Issue-31b", please update that branch with the latest commits of my branch "Issue-31". TIA!

**Comment by ghost** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Oliver,

sorry if I caused you extra work. I'm new to git and github. Could you
please send me a 'recipe' to merge master into #31, so I can continue
to work on it.

Thanks,
Egbert

On 23/01/16 06:15, Oliver Lau wrote:

> Thx, @egbrt https://github.com/egbrt! Cherry-picked f73dea4 
> <https://github.com/ola-ct/Qt-SESAM/commit/f73dea473dafb4ba1bf268bd99f
> 10a1d0a042dbd>.
> 
> Please do not add further commits to this pull-request, as it will
> produce next to unrecoverable merge conflicts.
> 
> If you'd like to continue your work on #31 
> https://github.com/ola-ct/Qt-SESAM/issues/31 please merge in
> "master" first.
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/ola-ct/Qt-SESAM/pull/112#issuecomment-174142953.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iEYEARECAAYFAlajeiIACgkQeg6UhOr0bBO2JQCg1l4+bHGei62O5ymDSJOZWBiJ
cuQAnRFVscqSmsrZVnpzLrcmYYzb4oF0
=mku0
-----END PGP SIGNATURE-----

**Comment by 607011** [comment]
@egbrt You want to fetch all changes from the parent repository before you make changes to your fork:

First, [configure a remote for your fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/).

Second, [sync the fork](https://help.github.com/articles/syncing-a-fork/).

Then you're free to make the desired changes to your fork. After extensive testing you may send me a pull-request. Thanks a lot in advance.

**Comment by 607011** [comment]
@egbrt Do the above every time directly before you push changes.

If `git pull` merged any changes from the parent repository, test again. Test particularly extensive if `git pull` has lead to merge conflicts. Thanks a lot in advance.

**Comment by ghost** [comment]
Dear Oliver,

I deleted my old fork and created a new fork to get rid of the Issue-31b
branch.

I've cloned my repository and fetched your repository to my local
computer. When I do

git checkout origin/Issue-31

git reports:

"You are in 'detached HEAD' state...."

Should I then create a new branch (which is what I did the previous
time) or what?

Cheers,
Egbert

**Comment by 607011** [comment]
@egbrt First, you can get rid of the unwanted branch by deleting it:
- Delete it locally: `git branch -d Issue-31b`
- Delete it remotely: `git push origin :Issue-31b`

Second, switch to another branch by typing just `git checkout branch_name`, e.g. `git checkout Issue-31`.

To make changes in branch "Issue-31" make them there. Don't branch the branch ;-)

**Comment by 607011** [comment]
@egbrt What exactly do you want to implement in branch "Issue-31"? It would be great if you implemented a feature to move items from one group to another.

**Comment by ghost** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

that's on my list.
Egbert

On 25/01/16 10:51, Oliver Lau wrote:

> @egbrt https://github.com/egbrt What exactly do you want to
> implement in branch "Issue-31"? It would be great if you
> implemented a feature to move items from one group to another.
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/ola-ct/Qt-SESAM/pull/112#issuecomment-174454216.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iEYEARECAAYFAlal8a4ACgkQeg6UhOr0bBPucQCgs5N4kSPRvPVUYU1iLAoUcYyS
IBkAoJTMw22O1lxR9AQCaC4IDuwrtOQd
=q4QA
-----END PGP SIGNATURE-----

**Comment by ghost** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

when I do |git checkout Issue-31|, git replies with

"error: pathspec 'Issue-31' did not match any file(s) known to git."

I'm missing something here, but what?

Egbert

On 25/01/16 10:44, Oliver Lau wrote:

> @egbrt https://github.com/egbrt First, you can get rid of the
> unwanted branch by deleting it.
> 
> Delete it locally: |git branch -d Issue-31b|.
> 
> Delete it remotely: |git push origin :Issue-31b|
> 
> Second, switch to another by typing just |git checkout
> branch_name|, e.g. |git checkout Issue-31|.
> 
> To make changes in branch "Issue-31" make them there. Don't branch
> the branch ;-)
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/ola-ct/Qt-SESAM/pull/112#issuecomment-174452225.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2

iEYEARECAAYFAlal82sACgkQeg6UhOr0bBN01QCfbuSTGkPAxodZ8zj+iMWWQry1
xxYAn1yeQ4EU614DOrfBoIII0l5tr/Rc
=5YYa
-----END PGP SIGNATURE-----

**Comment by 607011** [comment]
Great, @egbrt ! Let's continue the discussion in the [comments on #31](https://github.com/ola-ct/Qt-SESAM/issues/31#issuecomment-174457858).

**Comment by 607011** [comment]
@egbrt That's because `git clone …` only fetches "master". 

You can list all branches with `git branch -a`.

There you'll find an entry "remotes/origin/Issue-31".

To work on this branch in the local branch "Issue-31", just type the following:

`git checkout -b Issue-31 origin/Issue-31`

@egbrt Can you please turn off PGP signing of your posts? That's quite distracting ;-)

**Comment by ghost** [comment]
ok, thanks

**Pull request closed without merging**
